package webservicesserver;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2024-06-14T20:32:20.350+03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://www.dataaccess.com/webservicesserver/", name = "NumberConversionSoapType")
@XmlSeeAlso({ObjectFactory.class})
public interface NumberConversionSoapType {

  /**
   * Returns the word corresponding to the positive number passed as parameter. Limited to quadrillions.
   */
  @WebMethod(operationName = "NumberToWords")
  @RequestWrapper(localName = "NumberToWords", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.NumberToWords")
  @ResponseWrapper(localName = "NumberToWordsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.NumberToWordsResponse")
  @WebResult(name = "NumberToWordsResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
  public String numberToWords(

      @WebParam(name = "ubiNum", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
      java.math.BigInteger ubiNum
  );

  /**
   * Returns the non-zero dollar amount of the passed number.
   */
  @WebMethod(operationName = "NumberToDollars")
  @RequestWrapper(localName = "NumberToDollars", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.NumberToDollars")
  @ResponseWrapper(localName = "NumberToDollarsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", className = "com.dataaccess.webservicesserver.NumberToDollarsResponse")
  @WebResult(name = "NumberToDollarsResult", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
  public String numberToDollars(

      @WebParam(name = "dnum", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
      java.math.BigDecimal dnum
  );
}
